/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AlButton {
        "variant": string;
    }
}
declare global {
    interface HTMLAlButtonElement extends Components.AlButton, HTMLStencilElement {
    }
    var HTMLAlButtonElement: {
        prototype: HTMLAlButtonElement;
        new (): HTMLAlButtonElement;
    };
    interface HTMLElementTagNameMap {
        "al-button": HTMLAlButtonElement;
    }
}
declare namespace LocalJSX {
    interface AlButton {
        "variant"?: string;
    }
    interface IntrinsicElements {
        "al-button": AlButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "al-button": LocalJSX.AlButton & JSXBase.HTMLAttributes<HTMLAlButtonElement>;
        }
    }
}
